//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_HoroscopeService.DB_HoroscopeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DB_HoroscopeService.DB_WebService1Soap")]
    public interface DB_WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TP_HoroscopeService.DB_HoroscopeService.HelloWorldResponse HelloWorld(TP_HoroscopeService.DB_HoroscopeService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_HoroscopeService.DB_HoroscopeService.HelloWorldResponse> HelloWorldAsync(TP_HoroscopeService.DB_HoroscopeService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name firstName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT_UserData", ReplyAction="*")]
        TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataResponse INSERT_UserData(TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT_UserData", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataResponse> INSERT_UserDataAsync(TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TP_HoroscopeService.DB_HoroscopeService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TP_HoroscopeService.DB_HoroscopeService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_HoroscopeService.DB_HoroscopeService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TP_HoroscopeService.DB_HoroscopeService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class INSERT_UserDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="INSERT_UserData", Namespace="http://tempuri.org/", Order=0)]
        public TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataRequestBody Body;
        
        public INSERT_UserDataRequest() {
        }
        
        public INSERT_UserDataRequest(TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class INSERT_UserDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string computerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ipAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime birthDay;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime currentDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int Age;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Sign;
        
        public INSERT_UserDataRequestBody() {
        }
        
        public INSERT_UserDataRequestBody(string firstName, string lastName, string computerName, string ipAddress, System.DateTime birthDay, System.DateTime currentDate, int Age, string Sign) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.computerName = computerName;
            this.ipAddress = ipAddress;
            this.birthDay = birthDay;
            this.currentDate = currentDate;
            this.Age = Age;
            this.Sign = Sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class INSERT_UserDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="INSERT_UserDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataResponseBody Body;
        
        public INSERT_UserDataResponse() {
        }
        
        public INSERT_UserDataResponse(TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class INSERT_UserDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int INSERT_UserDataResult;
        
        public INSERT_UserDataResponseBody() {
        }
        
        public INSERT_UserDataResponseBody(int INSERT_UserDataResult) {
            this.INSERT_UserDataResult = INSERT_UserDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DB_WebService1SoapChannel : TP_HoroscopeService.DB_HoroscopeService.DB_WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DB_WebService1SoapClient : System.ServiceModel.ClientBase<TP_HoroscopeService.DB_HoroscopeService.DB_WebService1Soap>, TP_HoroscopeService.DB_HoroscopeService.DB_WebService1Soap {
        
        public DB_WebService1SoapClient() {
        }
        
        public DB_WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DB_WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DB_WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DB_WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_HoroscopeService.DB_HoroscopeService.HelloWorldResponse TP_HoroscopeService.DB_HoroscopeService.DB_WebService1Soap.HelloWorld(TP_HoroscopeService.DB_HoroscopeService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TP_HoroscopeService.DB_HoroscopeService.HelloWorldRequest inValue = new TP_HoroscopeService.DB_HoroscopeService.HelloWorldRequest();
            inValue.Body = new TP_HoroscopeService.DB_HoroscopeService.HelloWorldRequestBody();
            TP_HoroscopeService.DB_HoroscopeService.HelloWorldResponse retVal = ((TP_HoroscopeService.DB_HoroscopeService.DB_WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_HoroscopeService.DB_HoroscopeService.HelloWorldResponse> TP_HoroscopeService.DB_HoroscopeService.DB_WebService1Soap.HelloWorldAsync(TP_HoroscopeService.DB_HoroscopeService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_HoroscopeService.DB_HoroscopeService.HelloWorldResponse> HelloWorldAsync() {
            TP_HoroscopeService.DB_HoroscopeService.HelloWorldRequest inValue = new TP_HoroscopeService.DB_HoroscopeService.HelloWorldRequest();
            inValue.Body = new TP_HoroscopeService.DB_HoroscopeService.HelloWorldRequestBody();
            return ((TP_HoroscopeService.DB_HoroscopeService.DB_WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataResponse TP_HoroscopeService.DB_HoroscopeService.DB_WebService1Soap.INSERT_UserData(TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataRequest request) {
            return base.Channel.INSERT_UserData(request);
        }
        
        public int INSERT_UserData(string firstName, string lastName, string computerName, string ipAddress, System.DateTime birthDay, System.DateTime currentDate, int Age, string Sign) {
            TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataRequest inValue = new TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataRequest();
            inValue.Body = new TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.computerName = computerName;
            inValue.Body.ipAddress = ipAddress;
            inValue.Body.birthDay = birthDay;
            inValue.Body.currentDate = currentDate;
            inValue.Body.Age = Age;
            inValue.Body.Sign = Sign;
            TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataResponse retVal = ((TP_HoroscopeService.DB_HoroscopeService.DB_WebService1Soap)(this)).INSERT_UserData(inValue);
            return retVal.Body.INSERT_UserDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataResponse> TP_HoroscopeService.DB_HoroscopeService.DB_WebService1Soap.INSERT_UserDataAsync(TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataRequest request) {
            return base.Channel.INSERT_UserDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataResponse> INSERT_UserDataAsync(string firstName, string lastName, string computerName, string ipAddress, System.DateTime birthDay, System.DateTime currentDate, int Age, string Sign) {
            TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataRequest inValue = new TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataRequest();
            inValue.Body = new TP_HoroscopeService.DB_HoroscopeService.INSERT_UserDataRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.computerName = computerName;
            inValue.Body.ipAddress = ipAddress;
            inValue.Body.birthDay = birthDay;
            inValue.Body.currentDate = currentDate;
            inValue.Body.Age = Age;
            inValue.Body.Sign = Sign;
            return ((TP_HoroscopeService.DB_HoroscopeService.DB_WebService1Soap)(this)).INSERT_UserDataAsync(inValue);
        }
    }
}
